# name: Delivery Production

# on:
#   push:
#     branches:
#       - main
#     tags:
#       - "v*"

# jobs:
#   build-docker:
#     runs-on: ubuntu-22.04
#     environment: production

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Docker
#         uses: docker/setup-buildx-action@v1

#       - name: Log in to GitHub Docker Registry
#         uses: docker/login-action@v1
#         with:
#           registry: ghcr.io
#           username: ${{ github.repository_owner }}
#           password: ${{ secrets.GHCR_TOKEN }}

#       - name: Build and push Docker image
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           file: .docker/python/Dockerfile
#           push: true
#           tags: ghcr.io/michalskibinski109/sejm-stats:latest
#           target: prod
#           labels: |
#             org.opencontainers.image.source=${{ github.event.repository.html_url }}
#             org.opencontainers.image.revision=${{ github.sha }}
#             org.opencontainers.image.created=${{ steps.date.outputs.datetime }}
